
// class WebSocketRequestHandler;
// class WebSocketServer;
// class RequestHandlerFactory;
class GameGeom;
class Singleton;
class Shader;
class GameSound;
class GameMusic;
class FontWrapper;
class UIComponent;
class GameGUI;
class GameEntNode;
class GameEnt;
class GamePlantNode;
class GamePlant;
class GameBlock;
class GamePageHolder;
class GamePage;
class GameWorld;
class PooledResource;
class PoolManager;
class PoolPageManager;
